### PR TITLE
 now core logging functions can be modified by setLoggingFunctions function

### PR DESCRIPTION
**Pull request by jayadrathamondal**

### CODE REVIEW

**Comment by disjunction** [comment]
Hi @jayadrathamondal 
thanks for the pull request. I agree it's a good addition.

I would though remove getter/setter-functions and replace them with a direct property setting. This will correspond more to how the rest of the module is made.

The client code will then look like:
```js
logger.logFunctions.error = (...messages) => { /* ... */ }
```
By referencing through `module.exports.logFunctions` you enforce the referencing even if someone brutally replaces the entire object like:

```js
logger.logFunctions = { /* ... my functions ... */ } 
```
Also until now i used just the word "Log" instead of "Logging" in other functions, so I'd leave the same naming for the new property.

Would you like to change your PR accordingly or should I go forward and implement it?

**Comment by jayadrathamondal** [comment]
Hey @disjunction 
Yeah sure. I will change the PR accordingly. Thanks :+1:

**Comment by jayadrathamondal** [comment]
First of all I want to say that there is only `setLoggingFunctions` function exposed in module.exports.
So there is no way to access `loggingFunctions` & `getLoggingFunction` from outside.
So there is no way to make `logger.loggingFunctions = { /* ... my functions ... */ } `
But you can get this by this `logger.setLoggingFunctions({ /* ... my functions ... */  })`

If you remove getter/setter we will not be able to validate the functions user providing. May be user can do this `logger.loggingFunctions.error = null;` or `logger.loggingFunctions.error = 0`. It will make issue in run time in our module.
But if we use `setLoggingFunctions` we can add proper validations & can throw well defined reason before hand.

And regarding the name change of logging to log, I don't have any issue with that.

May be my approach is wrong. We can discuss those.

**Comment by jayadrathamondal** [comment]
Hey @disjunction , Sorry for the late reply. I missed the comment.
Yeah sure. I will change the PR accordingly.  But before that I want to do some clarifications.

First of all I want to say that there is only `setLoggingFunctions` function exposed in module.exports.
So there is no way to access `loggingFunctions` & `getLoggingFunction` from outside.
So there is no way to make `logger.loggingFunctions = { /* ... my functions ... */ } `
But you can get this by this `logger.setLoggingFunctions({ /* ... my functions ... */  })`

If you remove getter/setter we will not be able to validate the functions user providing. May be user can do this `logger.loggingFunctions.error = null;` , `logger.loggingFunctions.error = 0` or `logger.loggingFunctions = 0`. It will make issue in run time in our module.
But if we use `setLoggingFunctions` we can add proper validations & can throw well defined reason before hand.

And regarding the name change of logging to log, I don't have any issue with that.

May be my approach is wrong. We can discuss those.

**Comment by disjunction** [comment]
@jayadrathamondal  Your approach is not wrong, but it's not following the style I chose for this particular library. You follow OOP patterns for making intelligent software artifacts, which can be used by everyone. This library on contrary is a small and stupid module for intelligent developers.

Otherwise I'd have to use the same approach for the rest of the "hackable" functions, e.g. `transformEntry()`, `makeEntry()`, `applyLogFunction()` etc.

Still I kept your idea and already committed the changes and published it under version 1.2.0

I'm closing this pull request, but I'm still grateful to you for this PR

**Comment by jayadrathamondal** [comment]
@disjunction Cool. Thanks for adding my idea in your module. This module really helped me in my project.

Anyway, I have to add some more features in this module.

But as you said, I would like to make it intelligent for both intelligent & stupid developers. So I will start my own repository with this code base.

**Pull request closed without merging**
